import React from 'react';
import Link from 'next/link';

function HipaaNotice() {
    return (
        <main id="main" className="main">
            <div className="pagetitle">
                <div className='row pb-0 m-0 p-0'>
                    <div className='col-md-6 p-0'>
                        <h1>Standard HIPAA Notice v1 - 01-30-17</h1>
                    </div>
                </div>
            </div>
            <section>

                <div className='row pb-0'>

                    <div className='col-lg-12'>
                        <div className='card p-2'>
                            <div className='card-body pdf-form p-2'>
                                <h1 className='mb-3 border-bottom border-secondary text- fw-bold'>Company Name</h1>
                                <h2 className='mb-3'>HIPAA Notice of Privacy Practices ("Notice")</h2>
                                <h3 className='pdfhader p-1 text-14 fw-bold fst-italic'> THIS NOTICE DESCRIBES HOW INFORMATION ABOUT YOU MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS
INFORMATION. IT FURTHER DETAILS HOW YOU OR YOUR PERSONAL REPRESENTATIVE MAY GAIN ACCESS TO THIS INFORMATION. PLEASE
REVIEW CAREFULLY.</h3>

                                <p className='text-14'>If you have any questions about this Notice please contact our Privacy Contact, [CONTACT], at [NUMBER]. This Notice describes how our practice and
                                health care professionals, employees, volunteers, trainees and staff may use and disclose you medical information to carry out treatment, payment or health
                                care operations and for other purposes that are described in this Notice. We understand that medical information about you and your health is personal and
                                we are committed to protecting medical information about you. This Notice applies to all records of your care generated by this practice.</p>

                                <p className='text-14'>This Notice also describes your right to access and control your medical information. This information about you includes demographic information that may
                                identify you and that relates to your past, present and future physical or mental health or condition and related health care services. Typically your medical
                                information will include symptoms, examination and test results, diagnoses, treatment, and a plan for future care or treatment.</p>

                                <p className='text-14'>We are required by law to protect the privacy of your medical information and to follow the terms of this Notice. We may change the terms of this Notice at any
                                time. The new Notice will then be effective for all medical information that we maintain at that time and thereafter. We will provide you with any revised Notice if
                                you request a revised copy be sent to you in the mail or if you ask for one when you are in the office.
                                </p>

        <h4 className='pdfhader text-14 fw-bold'>I. Uses and Disclosures of Protected Health Information</h4>
        <p className='text-14'>
        Your medical information may be used and disclosed for purposes of treatment, payment and health care operations. The following
        are examples of different ways we use and disclose medical information. <span className='border-bottom'>These are examples only</span>.
        </p>
                                

        <ol type="a">
            <li><span className='fw-bold text-14'>Treatment</span><br />
                We may use and disclose medical information about you to provide, coordinate, or manage your medical treatment or any related services.
                This includes the coordination or management of your health care with a third party that has already obtained your permission to have access
                to your medical information. For example, we could disclose your medical information to a home health agency that provides care to you.
                We may also disclose medical information to other physicians who may be treating you, such as a physician to whom you have been referred
                to ensure that the physician has the necessary information to diagnose or treat you. In addition, we may disclose your medical information
                to another physician or health care provider, such as a laboratory.
            </li>
            <li><span className='fw-bold text-14'>Payment</span><br />
                We may use and disclose medical information about you to obtain payment for the treatment and services you receive from us. For example,
                we may need to provide your health insurance plan information about your treatment plan so that they can make a determination of eligibility
                or to obtain prior approval for planned treatment. For example, obtaining approval for a hospital stay may require that relevant medical
                information be disclosed to the health plan to obtain approval for the hospital admission.
            </li>

            <li><span className='fw-bold text-14'>Healthcare Operations</span><br />
                <p>
                We may use or disclose medical information about you in order to support the business activities of our practice. These
                activities include, but are not limited to, reviewing our treatment of you, employee performance reviews, training of medical
                students, licensing, marketing and fundraising activities and conducting or arranging for other business activities. 
                </p>   
                <p>
                For example, we may use a sign-in sheet at the registration desk where you will be asked to sign your name and indicate your
physician. We may call you by name in the waiting room when your physician is ready to see you. We may user or disclose
your medical information to remind you of your next appointment.
                </p>  
                <p>
                We may share your medical information with third party "business associates" that perform activities on our behalf, such as
billing or transcription for the practice. Whenever an arrangement between our office and a business associate involves that
use or disclosure of your medical information, we will have a written contract that contains terms that asks the "business
associate" to protect the privacy of your medical information.
                </p>      
                <p>
                We may use or disclose your medical information to provide you with information about treatment alternatives or other healthrelated benefits and services that may be of interest to you. We may also use and disclose your medical information for other
marketing activities. For example, your name and address may be used to send you a newsletter about our practice and the
services we offer. We may also send you information about products or services that we believe may be beneficial to you. You
may contact our Privacy Contact to request that these materials not be sent to you.
                </p>
                <p>
                We may use or disclose your demographic information and the dates that you received treatment from your physician, as
necessary, in order to contact you for fundraising activities supported by our office. If you do not want to receive these
materials, please contact our Privacy Contact to request that these fundraising materials not be sent to you.
                </p>
            </li>

            <li><span className='fw-bold text-14'>Healthcare Operations</span><br />
                <p>
                We, along with certain other health care providers and practice groups in the area, may participate in a health information
exchange ("Exchange"). An Exchange facilitates electronic sharing and exchange of medical and other individually identifiable
health information regarding patients among health care providers that participate in the Exchange. Through the Exchange we
may electronically disclose demographic, medical, billing and other health-related information about you to other health care
providers that participate in the Exchange and request such information for purposes of facilitating or providing treatment,
arrangement for payment for health care services or otherwise conducting or administering health care operations.

                </p>
            </li>         

       </ol>

       <h4 className='pdfhader text-14 fw-bold'>II. Other Permitted and Required Uses and Disclosures That May Be Made With Your Consent, Authorization or Opportunity to
       Object. </h4>
        <p className='text-14'>
        We may use and disclose your medical information in the following instances. You have the opportunity to agree or object to the use
        or disclosure of all or part of your medical information. If you are not present or able to agree or object to the use or disclosure of the
        medical information, then your physician may, using professional judgment, determine whether the disclosure is in your best interest.
        In this case, only the medical information that is relevant to your health care will be disclosed.
        </p>

        <ol type="a">
            <li><span className='fw-bold text-14'>Others Involved in Your Healthcare</span><br />
            <p>
            Unless you object, we may disclose to a member of your family, a relative, or a close friend your medical information that
            directly related to that person's involvement in your health care. If you are unable to agree or object to such a disclosure, we
            may disclose such information if we determine that it is in your best interest based on our professional judgment. We may use
            or disclose medical information to notify or assist in notifying a family member or any other person that is responsible for your
            care of your location, general condition or death. Finally, we may use or disclose your medical information to an entity assisting
            in disaster relief efforts and to coordinate uses and disclosures to family or other individuals involved in your health care.            
            </p>
            </li>
            <li><span className='fw-bold text-14'>Emergencies</span><br />
            <p>
            We may use or disclose your medical information for emergency treatment. If this happens, we shall try to obtain your consent
as soon as reasonable after the delivery of treatment. If the practice is required by law to treat you and has attempted to obtain
your consent but is unable to do so, the practice may still use or disclose your medical information to treat you.
            </p>
            </li>
            <li><span className='fw-bold text-14'>Communication Barriers</span><br />
            <p>
            We may use and disclose your medical information if the practice attempts to obtain consent from you but is unable to do so
due to substantial communication barriers and, in our professional judgment, you intended to consent to use or disclose under
the circumstances.
            </p>
            </li>


        </ol>

        <h4 className='pdfhader text-14 fw-bold'>III. Other Permitted and Required Uses and Disclosures That May Be Made Without Your Consent, Authorization or Opportunity to Object. </h4>
        <p className='text-14'>
        We may use or disclose your medical information in the following situations without your consent or authorization. These situations
include:
        </p>

        <ol type="a">
            <li><span className='fw-bold text-14'> Required By Law</span><br />
            <p>
            We may use or disclose your medical information when federal, state or local law requires disclosure. You will be notified of any
such uses or disclosure.
            </p>
            </li>

            <li><span className='fw-bold text-14'> Public Health</span><br />
            <p>
            We may disclose your medical information for public health activities and purposed to a public health authority that is permitted
by law to collect or receive the information. This disclosure will be made for the purpose of controlling disease, injury or
disability.
            </p>
            </li>

            <li><span className='fw-bold text-14'> Communicable Diseases</span><br />
            <p>
            We may disclose your medical information, if authorized by law, to a person who may have been exposed to a communicable
disease or may otherwise be at risk or contracting or spreading the disease or condition.
            </p>
            </li>

            <li><span className='fw-bold text-14'> Health Oversight</span><br />
            <p>
            We may disclose your medical information to a health oversight agency for activities authorized by law, such as audits,
investigations, inspections and licensure. These activities are necessary for the government agencies to oversee the health
care system, government benefit programs, other government regulatory programs and civil right laws.
            </p>
            </li>

            <li><span className='fw-bold text-14'> Abuse or Neglect</span><br />
            <p>
            We may disclose your medical information to a person or company required by the Food and Drug Administration to report
            adverse events, products defects or problems, biologic product deviations track products; to enable product recalls; to make
            repairs or replacements, or to conduct post marketing surveillance, as required.
            </p>
            </li>

            <li><span className='fw-bold text-14'> Legal Proceedings</span><br />
            <p>
            We may disclose medical information it the course of any judicial or administrative proceeding, when required by a court order
or administrative tribunal, and in certain conditions in response to a subpoena, discovery request or other lawful process.
            </p>
            </li>

            <li><span className='fw-bold text-14'> Legal Proceedings</span><br />
            <p>
            We may disclose medical information, so long as applicable legal requirements are met, for law enforcement purposes. These
            law enforcement purposes include: (i) responding to a court order, subpoena, warrant, summons or otherwise required by law;
            (ii) identifying or locating a suspect, fugitive, material witness or missing person; (iii) pertaining to victims of a crime; (iv)
            suspecting that death has occurred as a result of criminal conduct; (v) in the event that a crime occurs on the premises of the
            practice; and (vi) responding to a medical emergent (not on the Practice's premises) and it is likely that a crime has occurred.
            
            </p>
            </li>

            <li><span className='fw-bold text-14'> Coroners, Funeral Directors, and Organ Donors</span><br />
            <p>
            We may disclose medical information to a coroner or medical examiner for identification purposes, determining cause of death
or for the coroner or medical examiner to perform other duties authorized by law. We may also disclose medical information to
funeral directors as necessary to carry out their duties.            
            </p>
            </li>

            <li><span className='fw-bold text-14'> Research</span><br />
            <p>
            We may use and disclose your PHI for research purposes in certain limited circumstances. We will obtain your written
authorization to use your PHI for research purposes except when an Internal Review Board (“IRB”) or Privacy Board has
determined that the waiver of your authorization satisfies the following: (i) the use or disclosure involves no more than a
minimal risk to your privacy based on the following: (A) an adequate plan to protect the identifiers from improper use and
disclosure; (B) an adequate plan to destroy the identifiers at the earliest opportunity consistent with the research (unless there
is a health or research justification for retaining the identifiers or such retention is otherwise required by law); and (C) adequate,
written assurances that the PHI will not be re-used or disclosed to any other person or entity (except as required by law) for
authorized oversight of the research study, or for other research for which the use or disclosure would otherwise be permitted;
(ii) the research could not practicably be conducted without the waiver; and (iii) the research could not practicably be conducted
without access to and use of the PHI.            
            </p>
            </li>

            <li><span className='fw-bold text-14'>  Criminal Activity</span><br />
            <p>
            Consistent with applicable federal and state laws, we may disclose your medical information, if we believe that the use or
disclosure is necessary to prevent or lessen a serious and imminent threat to the health or safety of a person of the public. We
may also disclose medical information if it is necessary for law enforcement authorities to identify or apprehend an individual.           
            </p>
            </li>

            <li><span className='fw-bold text-14'>  Organ and Tissue Donation</span><br />
            <p>
            If you are an organ donor, we may release medical information to organizations that handle organ procurement or organ, eye
or tissue transplantation or to an organ donation bank, as necessary to facilitate organ or tissue donation and transplantation.           
            </p>
            </li>

            <li><span className='fw-bold text-14'>  Military Activity and National Security</span><br />
            <p>
            If you are a member of the armed forces, we may use or disclose medical information, (i) as required by military command
authorities; (ii) for the purpose of determining by the Department of Veteran Affairs of your eligibility for benefits; or (iii) for
foreign military personnel to the appropriate foreign military authority. We may also disclose your medial information to
authorized federal officials for conducting national security and intelligence activities, including for the protective services to the
President or others legally authorized.           
            </p>
            </li>

            <li><span className='fw-bold text-14'>  Worker's Compensation</span><br />
            <p>
            We may disclose your medical information as authorized to comply with workers' compensation laws and other similar
programs that provide benefits for work-related injuries or illness.          
            </p>
            </li>

            <li><span className='fw-bold text-14'>  Inmates</span><br />
            <p>
            We may use or disclose your medical information if you are an inmate or a correctional facility and our practice created or
            received your health information in the course of providing care to you.         
            </p>
            </li>

            <li><span className='fw-bold text-14'>  Required Uses and Disclosures</span><br />
            <p>
            Under the law, we must make disclosures to you and when required by the Secretary of the Department of Health and Human
Services to investigate or determine our compliance with the requirements of Section 164.500, et seq. seq.        
            </p>
            </li>
        </ol>

        <h4 className='pdfhader text-14 fw-bold'>IV. The Following Is a Statement of Your Rights with Respect to Your Medical Information and a Brief Description of How You
        May Exercise These Rights.
        </h4>
        <ol type="a">
            <li><span className='fw-bold text-14'> You have the right to inspect and copy your medical information.</span><br />
            <p>
            This means you may inspect and obtain a copy of medical information about you that has originated in our practice. We may
            charge you a reasonable fee for copying and mailing records. To the extent we maintain any portion of your PHI in electronic
            format, you have the right to receive such PHI from us in an electronic format. We will charge no more than actual labor cost to
            provide you electronic versions of your PHI that we maintain in electronic format.
            </p>
            <p>
            After you have made a written request to our Privacy Contact at the following address: [ADDRESS], we will have thirty (30)
days to satisfy your request. If we deny your request to inspect or copy your medical information, we will provide you with a
written explanation of the denial. You may not have a right to inspect or copy psychotherapy notes. In some circumstances, you
may have a right to have the decision to deny you access reviewed. Please contact the Privacy Contact if you have any
questions about access to your medical record.
            </p>
            </li>

            <li><span className='fw-bold text-14'> You have the right to request a restriction of your medical information.</span><br />
            <p>
            You may ask us not to use or disclose part of your medical information for the purposes of treatment, payment or healthcare
operations. You may also request that part of your medical information not be disclosed to family members or friends who may
be involved in your care or for notification purposes as described in this Notice. You must state in writing the specific restriction
requested and to whom you want the restriction to apply. You have the right to restrict information sent to your health plan or
insurer for products or services that you paid for solely out-of-pocket and for which no claim was made to your health plan or
insurer.
            </p>
            </li>

            <li><span className='fw-bold text-14'> We are not required to agree to your request.</span><br />
            <p>
            If we believe it is in your best interest to permit use and disclosure of your medical information, you medical information will not
be restricted; provided, however, we must agree to your request to restrict disclosure of your medical information if: (i) the
disclosure is for the purpose of carrying out payment or health care operations and is not otherwise required by law; and (ii) the
information pertains solely to a health care item or service for which you (and not your health plan) have paid us in full. If we do
agree to the requested restriction, we may not use or disclose your medical information in violation of that restriction unless it is
needed to provide emergency treatment. Your written request must be specific as to what information you want to limit and to
whom you want the limits to apply. The request should be sent, in writing, to our Privacy Contact.
            </p>
            </li>

            <li><span className='fw-bold text-14'> You have the right to request to receive confidential communications from us at a location other than your primary
            address. </span><br />
            <p>
            We will try to accommodate reasonable requests. Please make this request in writing to our Privacy Contact.
            </p>
            </li>

            <li><span className='fw-bold text-14'>You may have the right to have us amend your medical information.
            </span><br />
            <p>
            If you feel that medical information we have about you is incorrect or incomplete, you may request we amend the information. If
you wish to request an amendment to your medical information, please contact our Privacy Contact, in writing to request our
form Request to Amend Health Information. In certain cases, we may deny your request for an amendment. If we deny your request for amendment, you have the right to file a statement of disagreement with us.
            </p>
            </li>

            <li><span className='fw-bold text-14'>You have the right to receive an accounting of disclosures we have made, if any, of your medical information.
            </span><br />
            <p>
            This applies to disclosures for purposes other than treatment, payment or healthcare operations as described in this Notice. If
excludes disclosures we may have made to you, family members or friends involved in your care, or for notification purposes.
To receive information regarding disclosures made for a specific time period no longer than six (6) years and after April 14,
2003, please submit your request in writing to our Privacy Contact. We will notify you in writing of the cost involved in preparing
this list. To the extent we maintain your PHI in electronic format, you may request an accounting of all electronic disclosures of
your PHI for treatment, payment, or healthcare operations for the preceding three (3) years prior to such request.
            </p>
            </li>

            <li><span className='fw-bold text-14'>Uses and Disclosures of Protected Health Information Based Upon Your Written Authorization.
            </span><br />
            <p>
            Other uses and disclosures of your medical information not covered by this Notice or required by law will be made only with
            your written authorization. For example, most uses and disclosures of psychotherapy notes; PHI for marketing purposes; that
            constitute a sale of PHI and other than those described in this Notice, require authorization. You may revoke this authorization
            at any time, except to the extent that our practice has taken an action in reliance on the use or disclosure indicated in the prior
            authorization.            
            </p>
            </li>

            <li><span className='fw-bold text-14'>Right to be Notified of a Breach.
            </span><br />
            <p>
            You have the right to be notified in the event that our practice (or a Business Associate or ours) discovers a breach of
unsecured protected health information.          
            </p>
            </li>

            <li><span className='fw-bold text-14'>Complaints:
            </span><br />
            <p>
            You may complain to us or to the Secretary of Health and Human Services if you believe your privacy rights have been violated
by us. You may file a complaint with us by notifying our Privacy Contact, in writing. We will not retaliate against you for filing a
complaint.          
            </p>
            </li>

        </ol>

        <p className='text-12 text-secondary'>By signing this form, you acknowledge receiving this Notice and that you were afforded an opportunity to ask questions related to the content herein.</p>
        

                    </div>
                </div>
            </div>

                    <div className='col-lg-4'>
                        <div className='card pb-0 '>
                            <div className='card-header bg-blue2 text-white'> Signature of Patient or Patient's Representative</div>
                            <div className='card-body pb-0 mb-4 '>

                                <form className="row g-1">
                                    <div className="col-md-6">
                                        <div className='form-check text-12'>
                                            <input className="form-check-input" type="checkbox" id="hippa" />
                                            <label className="form-check-label" htmlFor="hippa"> &nbsp; X</label>
                                        </div>
                                    </div>
                                    <div className="col-md-6">
                                    <div className='form-check text-12 '>
                                    <input className="form-check-input" type="checkbox" id="hippa" />
                                    <label className="form-check-label" htmlFor="hippa"> &nbsp; Y</label>
                                </div>
                                    </div>

                                    <div className="col-md-12">
                                    <textarea cols={3} rows={4}  className="form-control form-control-sm" id="sign1" />
                                    </div>

                                    <div className="col-md-12">
                                    <div className='form-check text-12 '>
                                    <input className="form-check-input" type="checkbox" id="hippa" />
                                    <label className="form-check-label" htmlFor="hippa"> &nbsp; asndlasdnlas</label>
                                    </div>
                                    </div>

                                    <div className="col-md-12">
                                    <textarea cols={3} rows={4} className="form-control form-control-sm" id="sign2" />
                                    </div>

                                   

                                </form>
                            </div>
                        </div>
                    </div>

                    <div className='col-lg-4'>
                        <div className='card pb-0 '>
                            <div className='card-header bg-blue2 text-white'> Patient</div>
                            <div className='card-body pb-0 mb-4 '>

                                <form className="row g-1">
                                    <div className="col-md-12">
                                        <label htmlFor="billingcontact" className="form-label">Printed Name of Patient Representative</label>
                                        <input type="text" className="form-control form-control-sm" id="billingcontact" />
                                    </div>

                                    <div className="col-md-12">
                                        <label htmlFor="relationshippatient" className="form-label">Relationship to Patient</label>
                                        <input type="text" className="form-control form-control-sm" id="relationshippatient" />
                                    </div>
                                    <div className="col-md-12">
                                        <label htmlFor="address1" className="form-label">If not "Self," reason patient could not sign</label>
                                        <textarea cols={2} className="form-control form-control-sm" id="sign" />
                                    </div>
                                    
                                    <div className="col-md-12">
                                        <label htmlFor="city" className="form-label">Date</label>
                                        <input type="date" className="form-control form-control-sm" id="date" />
                                    </div>
                                    
                                </form>
                            </div>
                        </div>
                    </div>


                    <div className='col-lg-4'>
                    <div className='card pb-0 '>
                        <div className='card-header bg-blue2 text-white'> Company Representative</div>
                        <div className='card-body pb-0 mb-4 '>

                            <form className="row g-1">
                                <div className="col-md-12">
                                <label  className="form-label">Signature</label>
                                <textarea cols={3} rows={4}  className="form-control form-control-sm" id="sign1" />
                                </div>

                                <div className="col-md-12">
                                <label htmlFor="representativename" className="form-label">Name</label>
                                <input type="text" className="form-control form-control-sm" id="representativename" />
                                </div>

                            </form>
                        </div>
                    </div>
                </div>

                    <div className='text-center'>
                        <Link href="/orderentrylist" className='btn btn-success'><i className='bi bi-save'></i> Save</Link>&nbsp;
                        <button className='btn btn-secondary'><i className='bi bi-reply'></i> Reset</button>
                    </div>
                </div>
            </section>

        </main>
    )
}

export default HipaaNotice;